baseURL = "http://mthiele.eu"
languageCode = "de"
DefaultContentLanguage = "de"
title = "Michael Thiele"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
