  [[main]]
  name = "Home"
  identifier = "main"
  weight = 100
  url = "/"

  [[main]]
  name = "Über"
  weight = 300
  identifier = "about"
  url = "/de/about"

  [[main]]
  name = "Impressum"
  weight = 400
  identifier = "imprint"
  url = "/de/imprint"
